name: sciquest_stem_challenge
description: A comprehensive STEM quiz app with database integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.0
  # audioplayers: ^6.0.0 # REMOVED: Background music dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/audio/ # REMOVED: Audio asset declaration
